### ISSUE TITLE
Release 20160422 not tagged

### ISSUE THREAD

**Issue by xambroz** [libyal/libclocale#2]
Hi,
current version (20160422) not tagged in github? 
This would be probably the case for some other libs related to libewf 20160424 I guess. 
Please would it be possible to tag/releases ?
Thank you
Michal Ambroz

**Comment by joachimmetz** [comment]
Not sure what you mean.

Here are the released versions of libclocale https://github.com/libyal/libclocale/releases

HEAD or the current version is under development, not a release.

> Please would it be possible to tag/releases ?

If you're asking to tag HEAD with the version. Why?

**Comment by xambroz** [comment]
Hi,
the https://github.com/libyal/libclocale/blob/master/configure.ac says it is version 20160422, but it is not tagged. As I can see other packages were tagged in configure.ac around the same time I thought it means something - and that the release tag was just missing.
Mik

**Comment by joachimmetz** [comment]
> the https://github.com/libyal/libclocale/blob/master/configure.ac says it is version 20160422, but it is not tagged.

correct

> As I can see other packages were tagged in configure.ac around the same time I thought it means something - and that the release tag was just missing.

Not really, the tag is github's way to link a "release" to a specific "commit". You could derive there is a link between the two, but this is largely something github imposes.

This project (and the other libyal projects) use the following approach:
- version is defined in configure.ac
- source is managed in git on github
- versioned source package releases are provided via `make dist`
- when release is uploaded to github it adds a tag and zip and tar.gz of the source in git (which is completely useless for this project but cannot be turned off)

**Comment by joachimmetz** [comment]
Just pushed a new release with tag, closing issue.
