### ISSUE TITLE
Unable to build on windows using mingw

### ISSUE THREAD

**Issue by chrisbroome** [libyal/libclocale#3]
I'm currently unable to build `libclocale` on Windows.

## Steps to reproduce

Download and extract the source release for [libclocale](https://github.com/libyal/libclocale/releases/download/20180721/libclocale-alpha-20180721.tar.gz):

```
curl -L https://github.com/libyal/libclocale/releases/download/20180721/libclocale-alpha-20180721.tar.gz | tar zx
```

Change to the extracted folder:

```
cd libclocale-20180721
```

Configure the build (no errors here):

```
./configure --enable-winapi=yes
```

Build the source:

```
make
```

## Actual Result
Build fails with the following output:

```
C:/Program Files/Git/usr/bin/sh.exe ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../common  -DLOCALEDIR=\"/usr/local/share/locale\" -I../include -I../common -I../libcerror   -g -O2 -Wall -MT libclocale.lo -MD -MP -MF .deps/libclocale.Tpo -c -o libclocale.lo libclocale.c
Xlibclocale.Tpo -c -o libclocale.lo libclocale.lo
libtool: warning: libobj name 'libclocale.Tpo -c -o libclocale.lo libclocale.lo' may not contain shell special characters.
rm: unknown option -- c
Try 'rm --help' for more information.
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common "-DLOCALEDIR=\\/usr/local/share/locale\" -I../include -I../common -I../libcerror -g -O2 -Wall -MT libclocale.lo -MD -MP -MF .deps/libclocale.Tpo -c -o libclocale.lo libclocale.c"  -DDLL_EXPORT -DPIC -o .libs/libclocale.Tpo -c -o libclocale.lo libclocale.o
gcc.exe: error: libclocale.o: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.
make[1]: *** [Makefile:511: libclocale.lo] Error 1
make[1]: Leaving directory 'C:/Users/chris.broome/dist/libclocale-20180721/libclocale'
make: *** [Makefile:545: all-recursive] Error 1
```

## Expected Result
Build should succeed

**Comment by chrisbroome** [comment]
As a side comment, I first noticed this issue when trying to build [libbfio](https://github.com/libyal/libbfio)

**Comment by chrisbroome** [comment]
I *was* able to get this to build on `msys2`. One thing I noticed is that my `mingw` setup doesn't have a `/usr/share/locale` folder but `msys2` *does*. Would that make a difference?

**Comment by joachimmetz** [comment]
So MinGW builds are part of the CI tests: https://ci.appveyor.com/project/libyal/libclocale (mingw-gcc)

Have a look at https://github.com/libyal/libclocale/wiki/Building#using-minimalist-gnu-for-windows-mingw, https://github.com/libyal/libclocale/wiki/Building#using-msys-mingw and the appveyor configuration, this is likely an issue with the build environment.

If the issue still persist please attach the config.log

**Comment by chrisbroome** [comment]
Thanks for the quick response. My mingw environment was the one provided with Git for windows. I'll try using the standard mingw instead to see if I can repro the issue there.

**Comment by joachimmetz** [comment]
> My mingw environment was the one provided with Git for windows.

Not familiar with it (any links? since there are more than one git for windows solutions). I assume it might be missing some of the functionality libclocale needs. As indicated config.log might be able to provide more insight.

**Comment by chrisbroome** [comment]
Here's the link to download [Git for Windows](https://github.com/git-for-windows/git/releases/download/v2.21.0.windows.1/Git-2.21.0-64-bit.exe). It's an installer that sets up some basic things bash, git, and - importantly - mingw64. One weird issue is that it doesn't come with `mingw-get` out of the box.

Also, apparently this isn't even the preferred method for installing git on a Windows 10 machine anymore - the chocolately package manager is. As such, I probably don't need this stripped down mingw environment.

I'll look at the `config.log` as well to see if it can shed any light on the issue.

**Comment by chrisbroome** [comment]
This is now working correctly for me. You were absolutely right that it was a problem with my build environment. Thanks for your help!
